language: php

php:
    - 7.2

before_script: composer install

script: 
  - ./vendor/bin/phpunit
  - ./vendor/bin/php-cs-fixer fix src/
  - ./vendor/bin/php-cs-fixer fix tests/

notifications:
email:
  on_success: never
  on_failure: never